name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: the8thstar/Applio
        huggingface_repo_id: the8thstar/Applio
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN }}
